version: '3.7'
services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
    ports:
      - 5400:5432
    volumes:
      - ./postgresql15.1/data:/var/lib/postgresql/data

