version: '3.3'
services:
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
        restart: on-failure

    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
          - "9092:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
          - ./data:/var/run/docker.sock
        restart: on-failure
